config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    'help'    => 'static_pages#help'

  resources :games,  only: [ :new, :create, :index, :show ]
  resources :guesses,  only: [ :create, :show ]
end

app/models/game.rb
class Game < ActiveRecord::Base
  DEFAULT_LIVES = 7

  scope :with_game_status, -> (status) { where game_status: status }

  before_validation { self.game_status_id = GameStatus::STATUS_NEW unless self.game_status_id }
  validates :word, presence: true, length: { minimum: 3, maximum: 50 }
  validates :lives, presence: true, :numericality => { :greater_than_or_equal_to => 1 }
  validates :game_status_id, presence: true

  has_many   :guesses
  belongs_to :game_status

  def over?
    won? || lost?
  end

  def won?
    solved_char_status.all?
  end

  def solved_char_status
    # returns [ true, false, false ] etc
    upcase_chars.map do |c|
      guesses.any? { |guess| guess.letter == c }
    end
  end

  def lost?
    lives_left <= 0
  end

  def lives_left
    lives - wrong_guess_count
  end

  def update_status!
    self.game_status_id = calculate_status
  end

  private

  def wrong_guess_count
    guesses.reject { |guess| upcase_chars.include?(guess.letter) }.count
  end

  def upcase_chars
    @upcase_chars ||= word.upcase.chars
  end

  def calculate_status
    if won?
      GameStatus::STATUS_WON
    elsif lost?
      GameStatus::STATUS_LOST
    else
      GameStatus::STATUS_IN_PROGRESS
    end
  end
end

app/models/game_status.rb
class GameStatus < ActiveRecord::Base
  self.primary_key = "id"

  STATUS_NEW = 0
  STATUS_IN_PROGRESS = 1
  STATUS_LOST = 2
  STATUS_WON = 3

  validates :id, numericality: { only_integer: true, :greater_than_or_equal_to => STATUS_NEW, :less_than_or_equal_to => STATUS_WON }
end

app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :game

  default_scope -> { order(created_at: :asc) }

  before_validation { self.letter = letter.upcase }

  validates :letter, presence: true, length: { maximum: 1 },
                     format: { with: /\A[[:alpha:]]\z/},
                     uniqueness: { scope: [:game_id] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include HttpAcceptLanguage::AutoLocale

  rescue_from ActiveRecord::RecordNotFound, :with => :not_found

  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?

  protected

  def json_request?
    request.format.json?
  end

  def set_pagination_header(scope, options = {})
    request_params = request.query_parameters
    url_without_params = request.original_url.slice(0..(request.original_url.index("?") - 1 )) unless request_params.empty?
    url_without_params ||= request.original_url

    page = {}
    page[:first] = 1 if scope.total_pages > 1 && scope.previous_page
    page[:last] = scope.total_pages  if scope.total_pages > 1 && scope.next_page
    page[:next] = scope.next_page if scope.next_page
    page[:prev] = scope.previous_page if scope.previous_page

    headers["Link"] = page.each_with_object([]) do |(k, v), links|
      new_request_hash = request_params.merge({ :page => v })
      links << "<#{url_without_params}?#{new_request_hash.to_param}>; rel=\"#{k}\""
    end.join(", ")
  end

  def not_found
    respond_to do |format|
      format.html { render :file => File.join(Rails.root, 'public', '404.html') }
      format.json { render json: "{}", status: :bad_request }
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.where(nil)

    filtering_params.each do |key, value|
      @games = @games.public_send("with_#{key}", value) if value.present?
    end

    @games = @games.paginate(page: params[:page]).order('created_at ASC')

    respond_to do |format|
      format.html
      format.json { set_pagination_header(@games) }
    end
  end

  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @game = Game.new(lives: Game::DEFAULT_LIVES)
  end

  def create
    @game = Game.new(user_params.merge(game_status_id: GameStatus::STATUS_NEW))

    if @game.word.nil? || @game.word.empty?
      choose_random_word = ChooseRandomWord.new

      if choose_random_word.call
        @game.word = choose_random_word.word
      end
    end

    if @game.save
      respond_to do |format|
        format.html { redirect_to(@game) }
        format.json { render :show, status: :created, location: game_url(@game) }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @game.errors, status: :bad_request }
      end
    end
  end

  private

  def user_params
    params.require(:game).permit(:lives, :word)
  end

  def filtering_params
    params.slice(:game_status)
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  def create
    game_id = params[:game_id]
    @make_guess = MakeGuess.new(game_id, guess_params[:letter])

    if @make_guess.call
      respond_to do |format|
        format.html { redirect_to @make_guess.game }
        format.json { head :created, location: guess_url(@make_guess.guess) }
      end
    else
      flash[:danger] = @make_guess.errors.keys.map { |k| "#{k}: #{@make_guess.errors[k].to_sentence}"}.to_sentence

      respond_to do |format|
        format.html { redirect_to Game.find(params[:game_id]) }
        format.json { render json: @make_guess.errors, status: :bad_request }
      end
    end
  end

  private

  def guess_params
    params.require(:guess).permit(:letter)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/guess_helper.rb
module GuessHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <%= render 'shared/error_messages', object: @game %>

  <%= f.label :word %> <%= t('WORD_OPTIONAL') %>
  <%= f.text_field :word, class: 'form-control' %>

  <%= f.label :lives %>
  <%= f.number_field :lives, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/games/_game.html.erb
<tr>
  <td><%= game.id %></td>
  <td><%= t("STATUS_#{game.game_status_id}") %></td>
  <td><%= game.lives_left.to_s %></td>
  <td><%= game.over? ? (link_to t("SHOW_GAME_LINK"), game) : (link_to t("RESUME_GAME_LINK"), game) %></td>
</tr>

app/views/games/_guess.html.erb
<%= form_for(@game.guesses.build) do |f| %>
  <div>
    <%= hidden_field_tag :game_id, @game.id %><%= f.label :letter %><%= f.text_field :letter, class: 'form-control', autofocus: true %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/games/_status.html.erb
<div class="panel panel-default">
  <pre class="panel-body">
    <% if @game.won? %>
<%= t("WON_GAME_TEXT_html", { :word => @game.word }) %>
    <% elsif @game.lost? %>
<%= t("LOST_GAME_TEXT_html", { :word => @game.word }) %>
    <% else %>
<%= t("LIVES_LEFT_html", { :count => @game.lives_left }) %>:

<%= @game.solved_char_status.each_with_index.map { |status, index| status ? @game.word[index] : "_" }.join(" ") %>
    <% end %>

<%= t("USED_LETTERS") %>:
[ <%= @game.guesses.map(&:letter).join(" ") %> ]
  </pre>

  <div class="panel-footer">
    <% if !@game.over? %>
      <%= render 'guess' %>
    <% end %>
  </div>
</div>

app/views/games/index.html.erb
<% provide(:title, t("ALL_GAMES_TITLE")) %>
<h1><%= t("ALL_GAMES") %></h1>

<%= will_paginate %>

<table class="table table-striped">
  <tr>
    <th><%= t("OVERVIEW_GAME_ID") %></th>
    <th><%= t("OVERVIEW_GAME_STATUS") %></th>
    <th><%= t("OVERVIEW_GAME_LIVES_REMAINING") %></th>
    <th><%= t("OVERVIEW_GAME_LINK") %></th>
  </tr>
  <%= render @games %>
</table>

<%= will_paginate %>

app/views/games/new.html.erb
<% provide(:title, t("CREATE_GAME_TITLE")) %>
<% provide(:button_text, t("SAVE_GAME_BUTTON")) %>
<h1><%= t("CREATE_GAME") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/games/show.html.erb
<% provide(:title, t("GAME_TITLE")) %>
<% provide(:button_text, t("GUESS_BUTTON")) %>

<%= render 'status' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small><%=t :FOOTER_TEXT %></small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("HANGMAN"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("HOME_LINK"), root_path %></li>
        <li><%= link_to t("HISTORY_LINK"), games_path %></li>
        <li><%= link_to t("HELP_LINK"), help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= t("MAIN_TITLE") %></title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, t("HELP_TITLE")) %>
<h1><%= t :HELP_HEADING %></h1>
<p>
  <%= t :HELP_TEXT_html %>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, t("HOME_TITLE")) %>
<div class="center jumbotron">
  <h1><%=t :HOME_HEADING %></h1>
  <%= link_to t("HOME_PLAY_NOW"), 'games/new', class: "btn btn-lg btn-primary" %>
</div>